#ifndef MAINWINDOW_H
#define MAINWINDOW_H

#include <memory>
#include <QMainWindow>
#include "view.h"

class View;

namespace Ui {
    class MainWindow;
}

/**
 * @class MainWindow
 *
 * The main graphical user interface class (GUI class) for our application.
 */
class MainWindow : public QMainWindow {
    Q_OBJECT
public:
    MainWindow(QWidget *parent = 0);
    ~MainWindow();

private:
    // Auto-generated by Qt. DO NOT RENAME!
    Ui::MainWindow *ui;

private slots:
    void on_rainBox_toggled(bool checked);
    void on_fogBox_toggled(bool checked);
    void on_snowBox_toggled(bool checked);
    void on_aaBox_toggled(bool checked);
    void on_seaReflectionBox_toggled(bool checked);
    void on_seaRefractionBox_toggled(bool checked);
    void on_seaStormBox_toggled(bool checked);
    void on_seaShadowBox_toggled(bool checked);
    void on_ladderBox_toggled(bool checked);
    void on_lightBox_toggled(bool checked);
};

#endif // MAINWINDOW_H
